spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://192.168.1.60/glaceblog
    username: root
    password: z1x2c3v4
    driver-class-name: com.mysql.cj.jdbc.Driver